# Generated by Django 5.2.13 on 2026-05-31 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'HR AdmAdministrator'), ('MANAGER', 'Manger'), ('RPA_BOT', 'Automation Robot')], default='ADMIN', max_length=10),
        ),
    ]
