# Generated by Django 5.2.13 on 2026-04-26 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_reference', models.IntegerField(choices=[(1, 'Jan'), (2, 'Fev'), (3, 'Mar'), (4, 'Apr'), (5, 'May'), (6, 'Jun'), (7, 'Jul'), (8, 'Aug'), (9, 'Sep'), (10, 'Oct'), (11, 'Nov'), (12, 'Dec')], verbose_name='Reference month(1-12)')),
                ('year_reference', models.IntegerField(default=2026, verbose_name='Reference year')),
                ('work_load_average', models.FloatField(verbose_name='Workload Average/day')),
                ('hit_target', models.IntegerField(verbose_name='Hit target')),
            ],
        ),
        migrations.CreateModel(
            name='ReasonAbsenteeism',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Id')),
                ('code', models.IntegerField(unique=True, verbose_name='Reason of Absenteeism')),
                ('description', models.CharField(max_length=150, verbose_name='Description of the reason of absenteeism')),
            ],
        ),
        migrations.CreateModel(
            name='AbsenteeismRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.IntegerField(choices=[(1, 'Sunday'), (2, 'Monday'), (3, 'Tuesday'), (4, 'Wednesday'), (5, 'Thursday'), (6, 'Friday'), (7, 'Saturday')], verbose_name='Week Day')),
                ('season', models.IntegerField(choices=[(1, 'Summer'), (2, 'Autumn'), (3, 'Winter'), (4, 'Spring')], verbose_name='Season of the year')),
                ('transportation_expense', models.FloatField(verbose_name='Transportation expense')),
                ('disciplinary_failure', models.BooleanField(verbose_name='Disciplinary failure')),
                ('absenteeism_time', models.FloatField(verbose_name='Absenteeism time in Hours')),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absenteeism', to='employees.collaborator')),
                ('monthly_context', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='month_context', to='absenteeism.monthlycontext')),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reason', to='absenteeism.reasonabsenteeism')),
            ],
        ),
    ]
