# Generated by Django 5.2.13 on 2026-04-26 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EducationLevel",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=100, verbose_name="Description"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Collaborator",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                ("date_of_birth", models.DateField(verbose_name="Date of birth")),
                (
                    "service_years",
                    models.IntegerField(verbose_name="Service times in years"),
                ),
                (
                    "work_distance",
                    models.IntegerField(verbose_name="Distance from Residence to Work"),
                ),
                (
                    "education_level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="employees.educationlevel",
                        verbose_name="Education level",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FamiliarProfile",
            fields=[
                (
                    "id",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                (
                    "sons",
                    models.IntegerField(default=0, verbose_name="Quantity of sons"),
                ),
                (
                    "pets",
                    models.IntegerField(default=0, verbose_name="Quantity os pets"),
                ),
                (
                    "collaborator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="familiar_profile",
                        to="employees.collaborator",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HealthProfile",
            fields=[
                (
                    "id",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("weight", models.FloatField(verbose_name="Weight in Kg")),
                ("height", models.FloatField(verbose_name="Height in cm")),
                (
                    "bmi",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Body Mass Index"
                    ),
                ),
                (
                    "social_drinker",
                    models.BooleanField(default=False, verbose_name="Social drinker"),
                ),
                (
                    "social_smoker",
                    models.BooleanField(default=False, verbose_name="Social smoker"),
                ),
                (
                    "collaborator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_profile",
                        to="employees.collaborator",
                    ),
                ),
            ],
        ),
    ]
