# Generated by Django 5.2.13 on 2026-04-26 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborator',
            name='full_name',
            field=models.CharField(default=0, max_length=250, verbose_name='Full Name'),
            preserve_default=False,
        ),
    ]
